data_directory = "./sample"

ip_address = "127.0.0.1"
port = 8080
hostname = "localhost"

use_tls = false
certchain_pem_path = "tls/fullchain.pem"
key_pem_path = "tls/privkey.pem"

name = "Chorus Sample"
description = "A sample run of the Chorus relay"
#contact =
#public_key_hex =

user_hex_keys = [
  "ee11a5dff40c19a555f41fe42b48f00e618c91225622ae37b6c2bb67b76c4e49"
]

verify_events = true

# This is a bad idea in production, but useful for testing or for dumping
# your entire relay
allow_scraping = false

max_subscriptions = 32

serve_ephemeral = true
serve_relay_lists = true
